### ISSUE TITLE
Changing the shape of the curve?

### ISSUE THREAD

**Issue by cloudorbush** [max-prokopenko/react-native-ellipse-view#3]
Hi Max,

Is there any way to tinker with the radius of the ellipse?

I see there is a `borderRadius` prop that only works for android but it does nothing on iOS.

**Comment by max-prokopenko** [comment]
Hi! I've just added a [`roundness`](https://github.com/max-prokopenko/react-native-ellipse-view/tree/v0.2.4#props) prop in latest release. It should give at least some level of customisation of the ellipse. Let me know if it helps!
